### ISSUE TITLE
mcsat emory leak for QF_NRA formula

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#189]
Hi, for the following instance
~~~~
(set-logic QF_NRA)
(declare-const v0 Bool)
(declare-const r1 Real)
(declare-const r3 Real)
(declare-const v7 Bool)
(declare-const v8 Bool)
(declare-const r8 Real)
(assert (or v8 (= true v8 v8 (>= r8 (* r3 r3 r1 r1) 44487970 r1) v7 v7 v8 v0) v8 v0 v7 v7))
(push 1)
(assert (= true true (= (xor true v8 v7 (>= r8 (* r3 r3 r1 r1) 44487970 r1) v7 v0 v0) v8 v8 true v7 v7 v8 v0) (>= 1777358560 r1 (* r3 r3 r1 r1))))
(check-sat)
(pop 1)
(check-sat)
~~~~

When executing the command
~~~~
./yices_smt2 --mcsat --incremental fname.smt2
~~~~

asan detects a memory leak in yices2 (commit  cc89f91fbca18a)
~~~~
sat
sat
===============================================================
==29103==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 288 byte(s) in 36 object(s) allocated from:
    #0 0x7fded8562662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x7fded7d176f8 in __gmp_default_allocate (/usr/lib/x86_64-linux-gnu/libgmp.so.10+0x96f8)

SUMMARY: AddressSanitizer: 288 byte(s) leaked in 36 allocation(s).
~~~~

**Comment by dddejan** [comment]
I cannot reproduce this. Can you give more info on the build setup and architecture?

**Comment by dddejan** [comment]
I got it through valgrind and it seem it was a leak in libpoly. Should be fixed in https://github.com/SRI-CSL/libpoly/commit/3c7812ec8fe6ff0d5e41077799967d854929766d. My asan build didn't @rainoftime can you check if this fixes it.

**Comment by rainoftime** [comment]
It works.
