### ISSUE TITLE
Memory leak for QF_LRA and QF_BV formulas (--check-sat-assuming)

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#200]
Hi, for the following formula,
[leak-assume.txt](https://github.com/SRI-CSL/yices2/files/4496015/leak-assume.txt)

yices2 (commit 52d025a6b) throws a memory leak
~~~~
==30717==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7ff44ac85662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x828b7b in safe_malloc utils/memalloc.c:61
    #2 0x9a6601 in new_index_array context/assumption_stack.c:124
    #3 0x9a6f92 in cleanup_hash_index context/assumption_stack.c:213
    #4 0x9a8e0b in assumption_stack_pop context/assumption_stack.c:417
    #5 0x45e503 in context_pop context/context.c:5728
    #6 0x95d9cb in ctx_pop frontend/smt2/smt2_commands.c:3345
    #7 0x96ccf9 in smt2_pop frontend/smt2/smt2_commands.c:5843
    #8 0x980c2a in eval_smt2_pop frontend/smt2/smt2_term_stack.c:1004
    #9 0x530b82 in tstack_eval parser_utils/term_stack2.c:5436
    #10 0x97690c in smt2_parse frontend/smt2/smt2_parser.c:306
    #11 0x977fa1 in parse_smt2_command frontend/smt2/smt2_parser.c:927
    #12 0x40910d in main frontend/yices_smt2.c:739
    #13 0x7ff44936582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

**Comment by rainoftime** [comment]
A smaller QF_BV formula
~~~~
(set-option :produce-unsat-cores true)
(set-logic QF_BV)
(declare-const v6 Bool)
(declare-const v2 Bool)
(declare-const v13 Bool)
(declare-const v14 Bool)
(declare-const v17 Bool)
(declare-const bv_17-0 (_ BitVec 17))
(push 1)
(declare-const v19 Bool)
(declare-const v20 Bool)
(assert (! (=> v14 v14) :named IP_1))
(pop 1)
(assert (! (=> v13 (= ((_ repeat 6) bv_17-0) ((_ repeat 6) bv_17-0) ((_ repeat 6) bv_17-0) ((_ repeat 6) bv_17-0) ((_ repeat 6) bv_17-0))) :named IP_2))
(assert (! v2 :named IP_19))
(push 1)
(assert (! (xor v6 (= (bvudiv ((_ repeat 6) bv_17-0) ((_ repeat 6) bv_17-0)) (bvudiv ((_ repeat 6) bv_17-0) ((_ repeat 6) bv_17-0)) (bvudiv ((_ repeat 6) bv_17-0) ((_ repeat 6) bv_17-0)) ((_ repeat 6) bv_17-0) (bvudiv ((_ repeat 6) bv_17-0) ((_ repeat 6) bv_17-0))) v17 v13) :named IP_20))
(check-sat)
(check-sat-assuming (IP_9 IP_19))
~~~~
