### ISSUE TITLE
memory leak at safe_malloc utils/memalloc.c:61

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#238]
Hi, for the following query,
~~~~
(set-logic QF_ABV)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const bv_11-0 (_ BitVec 11))
(declare-const v2 Bool)
(declare-const arr-2878601033469301130_2878601033469301130-0 (Array (_ BitVec 19) (_ BitVec 19)))
(assert true)
(push 1)
(assert true)
(assert true)
(declare-const arr-2878601033443320530_2497745055729741690-0 (Array (_ BitVec 11) (Array (_ BitVec 19) (_ BitVec 19))))
(assert (distinct bv_11-0 bv_11-0 (bvmul bv_11-0 bv_11-0) (_ bv0 11) (_ bv0 11)))
(declare-const v3 Bool)
(assert true)
(declare-const arr-2878601033469301130_2878601033440072955-0 (Array (_ BitVec 19) (_ BitVec 8)))
(assert true)
(declare-const bv_30-0 (_ BitVec 30))
(declare-const v4 Bool)
(declare-const arr-2878601033440072955_6020763715132213282-0 (Array (_ BitVec 8) (Array (_ BitVec 11) (Array (_ BitVec 19) (_ BitVec 19)))))
(pop 1)
(declare-const v5 Bool)
(assert true)
(reset-assertions)
(check-sat)
(push 1)
(assert (= arr-2878601033469301130_2878601033469301130-0 arr-2878601033469301130_2878601033469301130-0 arr-2878601033469301130_2878601033469301130-0 arr-2878601033469301130_2878601033469301130-0 arr-2878601033469301130_2878601033469301130-0))
~~~~

yices2 b63cc30 throws a leak
~~~~
sat
(error "at line 26, column 12: undefined term: arr-2878601033469301130_2878601033469301130-0")

=================================================================
==4658==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f98227115b8 in __interceptor_malloc (/lib64/libasan.so.5+0x10c5b8)
    #1 0x714256 in safe_malloc utils/memalloc.c:61
    #2 0x68e0bc in make_pprod terms/power_products.c:484
    #3 0x691bda in build_pprod terms/pprod_table.c:204
    #4 0x70e84a in int_htbl_store_new_obj utils/int_hash_tables.c:294
    #5 0x70ebcb in int_htbl_get_obj utils/int_hash_tables.c:331
    #6 0x691e6e in get_pprod terms/pprod_table.c:228
    #7 0x691ffd in pprod_from_array terms/pprod_table.c:248
    #8 0x6920c3 in pprod_mul terms/pprod_table.c:263
    #9 0x63998c in bvarith64_buffer_mul_pp terms/bvarith64_buffers.c:428
    #10 0x63fc01 in bvarith64_buffer_mul_var terms/bvarith64_buffers.h:716
    #11 0x6417e6 in bvarith64_buffer_mul_term terms/bvarith64_buffer_terms.c:235
    #12 0x4e0edc in bva64_mul_elem parser_utils/term_stack2.c:2049
    #13 0x4e8ba7 in eval_mk_bv_mul parser_utils/term_stack2.c:4127
    #14 0x4ebf08 in tstack_eval parser_utils/term_stack2.c:5436
    #15 0x804c3c in smt2_parse frontend/smt2/smt2_parser.c:306
    #16 0x806320 in parse_smt2_command frontend/smt2/smt2_parser.c:927
    #17 0x4094a6 in main frontend/yices_smt2.c:739
    #18 0x7f98217c8554 in __libc_start_main (/lib64/libc.so.6+0x22554)
~~~~

**Comment by BrunoDutertre** [comment]
Fixed by 65181036482ef3676a46f010dd8930e6ed5e141f and 6c18c3cb6cf10bf63593b7ee35b2eaf936a91e4d.
