### ISSUE TITLE
Memory leak on QF_IDL formula at memalloc.c:61 

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#240]
Hi, for the formula,
[61.txt](https://github.com/SRI-CSL/yices2/files/4796829/61.txt)

yice2 305a8009 throws a leak
~~~~
sat

=================================================================
==47470==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fdcf9efb5b8 in __interceptor_malloc (/lib64/libasan.so.5+0x10c5b8)
    #1 0x7142f2 in safe_malloc utils/memalloc.c:61
    #2 0x4672c0 in context_get_edge_map context/context_utils.c:714
    #3 0x45e898 in analyze_diff_logic context/context_simplifier.c:3290
    #4 0x44e219 in _o_context_process_assertions context/context.c:5867
    #5 0x44ebac in context_process_assertions context/context.c:6017
    #6 0x44ec86 in assert_formulas context/context.c:6039
    #7 0x4225ac in yices_assert_formulas api/yices_api.c:8626
    #8 0x7f18d5 in check_delayed_assertions_assuming frontend/smt2/smt2_commands.c:3023
    #9 0x7fe73b in smt2_check_sat_assuming frontend/smt2/smt2_commands.c:6127
    #10 0x80daec in eval_smt2_check_sat_assuming frontend/smt2/smt2_term_stack.c:1058
    #11 0x4ebf08 in tstack_eval parser_utils/term_stack2.c:5436
    #12 0x804cd8 in smt2_parse frontend/smt2/smt2_parser.c:306
    #13 0x8063bc in parse_smt2_command frontend/smt2/smt2_parser.c:927
    #14 0x4094a6 in main frontend/yices_smt2.c:739
    #15 0x7fdcf8fb2554 in __libc_start_main (/lib64/libc.so.6+0x22554)

SUMMARY: AddressSanitizer: 24 byte(s) leaked in 1 allocation(s).
~~~~

**Comment by rainoftime** [comment]
Related the final line 
~~~~
(check-sat-assuming ())
~~~~
