### ISSUE TITLE
QF_ABV error in building function solver model

### ISSUE THREAD

**Issue by aman-goel** [SRI-CSL/yices2#287]
Hi,

For the attached QF_ABV SMT-LIB2 problem, the current Yices master (448f94b3422502475a1bcfa23101ec6f9d4057e3) results in an assertion failure during building a function solver model, as follows:

```
yices_smt2: solvers/funs/fun_solver.c:3486: build_maps_for_type: Assertion `solver->reconciled && is_finite_type(solver->types, sigma) && !type_has_finite_domain(solver->types, tau)' failed.
```

This SMT problem has been generated during word-level hardware model checking, and contains arrays with domain and range as bitvectors.

In general, I have seen segmentation faults in Yices (release build mode through Yices C API) for similar QF_ABV problems when building a function model. Unfortunately, these errors don't appear for simpler problems. Here is a backtrace from gdb (if it is of any help):
```c
(gdb) bt
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000000001fc15ed in abort ()
#2  0x00000000006bfe0f in fix_base_maps (solver=0x32644c0, store=0x44b5c70, 
    f=0x31820e0, v=0x31c2250, n=38) at solvers/funs/fun_solver.c:3379
#3  0x00000000006c018d in build_maps_for_type (solver=0x32644c0, tau=8, n=38, 
    v=0x31c2250, tree=0x7fffffff9320, store=0x44b5c70)
    at solvers/funs/fun_solver.c:3489
#4  0x00000000006c02c9 in fun_solver_build_maps (solver=0x32644c0, 
    v=0x7fffffff9310, tree=0x7fffffff9320, store=0x44b5c70)
    at solvers/funs/fun_solver.c:3539
#5  0x00000000006c03c7 in fun_solver_build_model (solver=0x32644c0, 
    store=0x44b5c70) at solvers/funs/fun_solver.c:3594
#6  0x00000000006ac92f in egraph_build_model (egraph=0x32bc6c0, vtbl=0x32320e0)
    at solvers/egraph/egraph.c:7940
#7  0x000000000062dbdb in build_model (model=0x32320e0, ctx=0x32d2210)
    at context/context_solver.c:1073
#8  0x000000000062dd2e in context_build_model (model=0x32320e0, ctx=0x32d2210)
    at context/context_solver.c:1122
#9  0x000000000060f1c0 in _o_yices_get_model (ctx=0x32d2210, keep_subst=1)
    at api/yices_api.c:9316
#10 0x000000000060f15b in yices_get_model (ctx=0x32d2210, keep_subst=1)
    at api/yices_api.c:9303
```

Please feel free to ask for any further details if needed.

Attached:  [bv_array_error.smt2.txt](https://github.com/SRI-CSL/yices2/files/5087363/bv_array_error.smt2.txt)

Thank you.

--
Aman

**Comment by BrunoDutertre** [comment]
Hi @aman-goel,

This should be fixed now. (commit 24e4b0d570caf6d9afdbe3dcbb65d4af0f994a17)

**Comment by aman-goel** [comment]
Thanks!
