### ISSUE TITLE
Double free at io/tracer.c:89 on a formula with only set-options

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#304]
Hi, for the following formula
~~~~
(set-option :verbosity 3)
(set-option :diagnostic-output-channel "/dev/null")
~~~~
yices 5019920
~~~~
=================================================================
=================================================================
==29415==ERROR: AddressSanitizer: attempting double-free on 0x61600000f980 in thread T0:
    #0 0x7fa2c6cd232a in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9832a)
    #1 0x7fa2c6118372 in fclose (/lib/x86_64-linux-gnu/libc.so.6+0x6d372)
    #2 0x7fa2c6cd182d in fclose (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9782d)
    #3 0x4982b9 in delete_trace io/tracer.c:89
    #4 0x7f8163 in delete_tracer frontend/smt2/smt2_commands.c:1902
    #5 0x8044ae in delete_smt2_globals frontend/smt2/smt2_commands.c:4653
    #6 0x804673 in delete_smt2 frontend/smt2/smt2_commands.c:4766
    #7 0x40a146 in main frontend/yices_smt2.c:1122
    #8 0x7fa2c60cb83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #9 0x407298 in _start (/home/rainoftime/Work/tofuzz/yices2/build/x86_64-pc-linux-gnu-debug/bin/yices_smt2+0x407298)

0x61600000f980 is located 0 bytes inside of 552-byte region [0x61600000f980,0x61600000fba8)
freed by thread T0 here:
    #0 0x7fa2c6cd232a in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9832a)
    #1 0x7fa2c6118372 in fclose (/lib/x86_64-linux-gnu/libc.so.6+0x6d372)

previously allocated by thread T0 here:
    #0 0x7fa2c6cd2662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x7fa2c6118cec  (/lib/x86_64-linux-gnu/libc.so.6+0x6dcec)

SUMMARY: AddressSanitizer: double-free ??:0 __interceptor_free
==29415==ABORTING

~~~~

**Comment by BrunoDutertre** [comment]
Fixed in 8c90a0b62f7170b4acdd93bf4f60fb9bbb8de8eb.
