### ISSUE TITLE
Memory leak at safe_malloc utils/memalloc.c:62

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#325]
Hi，for this formula 
~~~~
(set-logic QF_LRA)
(declare-fun _substvar_906_ () Real)
(declare-fun _substvar_2459_ () Bool)
(declare-fun _substvar_905_ () Real)
(assert (> 0.0 (ite _substvar_2459_ (* _substvar_905_ _substvar_906_) 0.0)))
~~~~
yices 4692d8db85a6 (built without mcsat) throws a leak 

~~~~
./yices_smt2 --incremental f.smt2
~~~~

~~~~
(error "non-linear arithmetic is not allowed in logic QF_LRA")

=================================================================
==852==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 160 byte(s) in 1 object(s) allocated from:
    #0 0x7f16de4a1662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x846932 in safe_malloc utils/memalloc.c:62
    #2 0x77aa03 in init_ite_stack terms/ite_stack.c:38
    #3 0x48c69b in init_ite_flattener context/ite_flattener.c:31
    #4 0x442717 in flatten_ite_to_arith context/context.c:1106
    #5 0x443051 in map_ite_to_arith context/context.c:1186
    #6 0x44d7d1 in internalize_to_arith context/context.c:2828
    #7 0x453e1b in assert_toplevel_arith_geq context/context.c:4145
    #8 0x4577ec in assert_toplevel_formula context/context.c:4685
    #9 0x45f9e6 in context_process_assertions context/context.c:6054
    #10 0x45fea9 in _o_assert_formulas context/context.c:6117
    #11 0x46099b in assert_formulas context/context.c:6177
    #12 0x4609c1 in assert_formula context/context.c:6197
    #13 0x87f0a3 in add_assertion frontend/smt2/smt2_commands.c:3421
    #14 0x892297 in smt2_assert frontend/smt2/smt2_commands.c:6529
    #15 0x8a6bf0 in eval_smt2_assert frontend/smt2/smt2_term_stack.c:1212
    #16 0x5363ce in tstack_eval parser_utils/term_stack2.c:5477
    #17 0x89b88a in smt2_parse frontend/smt2/smt2_parser.c:316
    #18 0x89cfe6 in parse_smt2_command frontend/smt2/smt2_parser.c:967
    #19 0x406bf5 in main frontend/yices_smt2.c:1094
    #20 0x7f16dd0bd83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
~~~~

**Comment by BrunoDutertre** [comment]
Fixed by  1d5672c9a4e5147e9cc50c31dd896882434aee8d.
