### ISSUE TITLE
debian apt instruction fail 

### ISSUE THREAD

**Issue by Matafou** [SRI-CSL/yices2#399]
Hi.
when I try the instruction for debian installation I get a warning and an error. The warnig is because the trust mechanism has changed a bit in debian. The error seems to be because the server is not responding anymore.

Best regards

```
sudo add-apt-repository ppa:sri-csl/formal-methods
```
 gives
```
 More info: https://launchpad.net/~sri-csl/+archive/ubuntu/formal-methods
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpvjf41uq9/pubring.gpg' created
gpg: /tmp/tmpvjf41uq9/trustdb.gpg: trustdb created
gpg: key FA8E1301F4D3932C: public key "Launchpad PPA for SRI-CSL" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.9/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.9/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.9/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.browser'
```

and then
```
sudo apt update
```
gives 
```
...
Err:9 http://ppa.launchpad.net/sri-csl/formal-methods/ubuntu jammy Release                                                                                                                                        
  404  Not Found [IP: 91.189.95.85 80

**Comment by ianamason** [comment]
Better build from source then. It is pretty easy.

**Comment by Matafou** [comment]
Indeed I did. It was just to warn about the outdated info on the website.

**Comment by disteph** [comment]
How about now? ianamason has added jammy.

**Comment by Matafou** [comment]
Seems to work, modulo the pgp thing. I will try to see the correct procedure for the signature.

**Comment by tbmreza** [comment]
Still failing in 2024.
```
$ sudo add-apt-repository ppa:sri-csl/formal-methods
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'```

**Comment by ahmed-irfan** [comment]
It should be working now. Please open this issue again if it doesn't work for you.
