### ISSUE TITLE
Assertion failure in parser

### ISSUE THREAD

**Issue by dddejan** [SRI-CSL/yices2#62]
The input is at https://gist.github.com/dddejan/365b20b75e7b4fee90ec6e9a24e1abc9

With result:
```
terms/term_manager.c:1623: remove_monomials: Assertion `x < a[i]' failed.
```

Backtrace:
```
#0  0x00007ffff7541428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff754302a in __GI_abort () at abort.c:89
#2  0x00007ffff7539bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7a750b "x < a[i]", file=file@entry=0x7a70b9 "terms/term_manager.c", line=line@entry=1623,
    function=function@entry=0x7a8330 <__PRETTY_FUNCTION__.10703> "remove_monomials") at assert.c:92
#3  0x00007ffff7539c82 in __GI___assert_fail (assertion=0x7a750b "x < a[i]", file=0x7a70b9 "terms/term_manager.c", line=1623, function=0x7a8330 <__PRETTY_FUNCTION__.10703> "remove_monomials") at assert.c:101
#4  0x00000000005ece23 in remove_monomials (manager=0xb57b40 <manager>, p=0xe07240, a=0xc322d0, c=0xb57b98 <manager+88>) at terms/term_manager.c:1623
#5  0x00000000005ed71e in mk_integer_polynomial_ite (manager=0xb57b40 <manager>, c=63622, t=41878, e=4072) at terms/term_manager.c:1762
#6  0x00000000005eea52 in mk_ite (manager=0xb57b40 <manager>, c=63622, t=41878, e=4072, tau=1) at terms/term_manager.c:2046
#7  0x0000000000411d85 in yices_ite (cond=63623, then_term=4072, else_term=41878) at api/yices_api.c:2711
#8  0x00000000004c430b in eval_mk_ite (stack=0xb57360 <stack>, f=0x18ec870, n=3) at parser_utils/term_stack2.c:3158
#9  0x00000000004cd7a0 in tstack_eval (stack=0xb57360 <stack>) at parser_utils/term_stack2.c:5351
#10 0x00000000006a2264 in smt2_parse (parser=0xb57340 <parser>, start=c0) at frontend/smt2/smt2_parser.c:270
#11 0x00000000006a45ae in parse_smt2_command (parser=0xb57340 <parser>) at frontend/smt2/smt2_parser.c:839
#12 0x000000000040753f in main (argc=2, argv=0x7fffffffe518) at frontend/yices_smt2.c:468
```

**Comment by BrunoDutertre** [comment]
Fixed in 24d6661
